obj-m += cmdq_platform_mt6789.o
ccflags-y += -DCONFIG_MTK_CMDQ_MBOX_EXT=1 -DCONFIG_MMPROFILE=1 -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)
ccflags-y += -I$(src)/../include/include
