obj-m += mtk_dynamic_loading_throttling.o
ccflags-y += -DCONFIG_MTK_DYNAMIC_LOADING_POWER_THROTTLING=1 -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)
