obj-m += tcpc_rt1711h.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)  -DCONFIG_MTK_TYPEC_WATER_DETECT=1 -DCONFIG_PD_DBG_INFO=1 -DCONFIG_PRIZE_TYPEC_POSITIVE_NEGATIVE=1 -DCONFIG_TCPC_CLASS=1 -DCONFIG_USB_POWER_DELIVERY=1 -DCONFIG_WAIT_TX_RETRY_DONE=1
ccflags-y += -I$(src)/../include
