obj-m += mtk_scpsys.o
mtk_scpsys-objs := mtk-scpsys-common.o mtk-scpsys-mt6789.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) -DCONFIG_PM=1
ccflags-y += -I$(src)/../include
