obj-m += mtk_btcvsd.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)
ccflags-y += -I$(src)/../include
include $(src)/../include/mindone/flags-audio.mk
