obj-m += main3af.o
main3af-objs := main3_lens.o BU24253AF.o GT9772AF.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)  -DCONFIG_OF=1
ccflags-y += -I$(src)/../include
