obj-m += log_store.o
ccflags-y += -DCONFIG_MTK_DRAM_LOG_STORE=1 -DCONFIG_MTK_DRAM_LOG_STORE_SIZE=0x100 -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) 
