obj-m += spi_mt65xx.o
# MINDONE-SPI-TEECLK (F3285): header for the trusted-execution-environment clock manager
ccflags-y += -I$(src)/../include
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)  -DCONFIG_SPI_FSL_SPI=1
