obj-m += spmi_mtk_pmif.o
spmi_mtk_pmif-objs := spmi-mtk-pmif-core.o spmi-mtk-debug.o
ccflags-y += -Wno-error -Wno-error=implicit-int -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)  -I$(src)/../include/drivers/misc/mediatek/include -DCONFIG_MTK_HANG_DETECT=1
