obj-m += subaf.o
subaf-objs := sub_lens.o BU6424AF.o BU6429AF.o DW9714AF.o DW9814AF.o DW9718AF.o LC898214AF.o WV511AAF.o AK7371AF.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) 
ccflags-y += -I$(src)/../include
