obj-m += mtk_dvfsrc_devfreq.o
ccflags-y += -DCONFIG_MTK_DVFSRC_MODULE=1 -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) 
ccflags-y += -DCONFIG_MTK_DVFSRC=1
ccflags-y += -I$(src)/../include/include
