# ../include/: MediaTek platform headers mirrored at their kernel-tree paths (shared by all modules)
obj-m += rpmb_mtk.o
ccflags-y += -Wno-error -Wno-error=implicit-int -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)  -I$(src)/../include/drivers/scsi/ufs -I$(src)/../include/drivers/scsi/ufs/vendor -I$(src)/../include/drivers/mmc/host -I$(src)/../include/drivers/mmc/core
ccflags-y += -I$(src)/../include
