obj-m += mtk_slbc.o
mtk_slbc-objs := slbc.o
ccflags-y += -DCONFIG_MTK_SLBC=1 -DCONFIG_MTK_SLBC_IPI=1 -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)
