obj-m += mtk_swpm.o
mtk_swpm-objs := swpm_module.o swpm_module_ext.o mtk_swpm_common_sysfs.o mtk_swpm_sysfs_procfs.o
ccflags-y += -I$(src) -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion
