# ../include/: MediaTek platform headers mirrored at their kernel-tree paths (shared by all modules)
obj-m += mtk-swpm-dbg-common-v1.o
mtk-swpm-dbg-common-v1-y += swpm_dbg_fs_common.o
ccflags-y += -Wno-error -I$(src) -I$(src)/../include/include -I$(src)/../include/drivers/misc/mediatek/include -I$(src)/../include/drivers/misc/mediatek/swpm/inc -I$(src)/../include/drivers/misc/mediatek/swpm/modules/include -I$(src)/../include/drivers/misc/mediatek/swpm/mtk_swpm_fs
