obj-m += main2af.o
main2af-objs := main2_lens.o AW86014AF.o AW86014PCSRAF.o AK7371AF.o AK7374AF.o bu64748_function.o bu64748af.o LC89821x_STMV.o LC898212XDAF_F.o LC898217AF.o LC898217AFA.o LC898217AFB.o LC898217AFC.o DW9718TAF.o GT9772AF.o AW86017CSRAF.o DW9800WAF.o
ccflags-y += -DCONFIG_OF=1 -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) 
ccflags-y += -I$(src)/../include
