# ../include/: MediaTek platform headers mirrored at their kernel-tree paths (shared by all modules)
obj-m += mtk_scp_vow.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) -I$(src)/../include/sound/soc/mediatek/common -I$(src)/../include/sound/soc/mediatek/vow -I$(src)/../include/drivers/misc/mediatek/scp/include -I$(src)/../include/drivers/misc/mediatek/vow/ver02
