obj-m += clk_fmeter_mt6789.o
clk_fmeter_mt6789-objs := clk_fmeter_mt6789_core.o clk-fmeter.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)  -I$(src)/../include
