obj-m += trace_mmstat.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)  -DCONFIG_MTK_GPU_SUPPORT=1 -DCONFIG_MTK_ION=1 -DCONFIG_ZSMALLOC=1
