obj-m += tinysys_scmi.o
tinysys_scmi-objs := tinysys-scmi-drv.o tinysys.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) -I$(srctree)/drivers/firmware/arm_scmi
ccflags-y += -I$(src)/../include
