obj-m += mtk_low_battery_throttling.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) 
ccflags-y += -DCONFIG_PMIC_LBAT_SERVICE=1
