obj-m += teeperf.o
teeperf-objs := main.o user.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) 
ccflags-y += -I$(src)/../include
