obj-m += mt6358_battery.o
mt6358_battery-objs := mtk_battery_coulomb_service.o mtk_battery.o mtk_battery_algo.o mt6358-gauge.o mtk_battery_daemon.o
ccflags-y += -Wno-error -I$(src)
ccflags-y += -I$(src)/../include
