# vendor-headers/: MediaTek platform headers mirrored at their kernel-tree paths
obj-m += extcon_mtk_usb.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) -I$(src)/vendor-headers -I$(src)/vendor-headers/drivers/power/supply -I$(src)/../include

