obj-m += sub2af.o
sub2af-objs := sub2_lens.o DW9718SAF.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)  -DCONFIG_OF=1
ccflags-y += -I$(src)/../include
