obj-m += clk_dbg_mt6789.o
clk_dbg_mt6789-objs := clkdbg-mt6789.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)  -I$(src)/../include
