obj-m += mtk_swpm_perf_arm_pmu.o
mtk_swpm_perf_arm_pmu-objs := swpm_perf_arm_pmu.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)
