load(
    "//build/kernel/kleaf:kernel.bzl",
    "kernel_abi",
    "kernel_build",
    "kernel_compile_commands",
    "kernel_modules_install",
)

package(default_visibility = ["//visibility:public"])

_MINDONE_IN_TREE_MODULES = [
    "6lowpan.ko",
    "8021q.ko",
    "9pnet_fd.ko",
    "9pnet.ko",
    "aes-neon-blk.ko",
    "aqc111.ko",
    "asix.ko",
    "ax88179_178a.ko",
    "bluetooth.ko",
    "bsd_comp.ko",
    "btbcm.ko",
    "btqca.ko",
    "btsdio.ko",
    "can-bcm.ko",
    "can-dev.ko",
    "can-gw.ko",
    "can.ko",
    "can-raw.ko",
    "cctrng.ko",
    "cdc-acm.ko",
    "cdc_eem.ko",
    "cdc_ether.ko",
    "cdc_ncm.ko",
    "cfg80211.ko",
    "clk-gate_test.ko",
    "clk_kunit_helpers.ko",
    "clk-test.ko",
    "dev_addr_lists_test.ko",
    "efivarfs.ko",
    "ext4-inode-test.ko",
    "exynos-hvm.ko",
    "fat_test.ko",
    "ftdi_sio.ko",
    "gnss.ko",
    "gzvm.ko",
    "hci_uart.ko",
    "hidp.ko",
    "hid-uclogic-test.ko",
    "ieee802154_6lowpan.ko",
    "ieee802154.ko",
    "ieee802154_socket.ko",
    "iio-test-format.ko",
    "industrialio-triggered-buffer.ko",
    "input_test.ko",
    "kfifo_buf.ko",
    "kheaders.ko",
    "kunit-example-test.ko",
    "kunit.ko",
    "kunit-test.ko",
    "l2tp_core.ko",
    "l2tp_ppp.ko",
    "libarc4.ko",
    "lib_test.ko",
    "mac80211.ko",
    "mac802154.ko",
    "macsec.ko",
    "mediatek-cpufreq-hw.ko",
    "mii.ko",
    "netfs.ko",
    "nfc.ko",
    "nhc_dest.ko",
    "nhc_fragment.ko",
    "nhc_hop.ko",
    "nhc_ipv6.ko",
    "nhc_mobility.ko",
    "nhc_routing.ko",
    "nhc_udp.ko",
    "of_kunit_helpers.ko",
    "open-dice.ko",
    "phy-generic.ko",
    "platform-test.ko",
    "ppp_deflate.ko",
    "ppp_generic.ko",
    "ppp_mppe.ko",
    "pppox.ko",
    "pps_core.ko",
    "pptp.ko",
    "pstore_blk.ko",
    "pstore_zone.ko",
    "ptp.ko",
    "ptp_kvm.ko",
    "pwrseq-core.ko",
    "r8152.ko",
    "r8153_ecm.ko",
    "regmap-kunit.ko",
    "regmap-ram.ko",
    "regmap-raw-ram.ko",
    "rfcomm.ko",
    "rfkill.ko",
    "rtl8150.ko",
    "slcan.ko",
    "slhc.ko",
    "snd-hda-codec-hdmi.ko",
    "snd-soc-audio-graph-card.ko",
    "snd-soc-simple-card-utils.ko",
    "soc-topology-test.ko",
    "soc-utils-test.ko",
    "time_test.ko",
    "tipc_diag.ko",
    "tipc.ko",
    "usbmon.ko",
    "usbnet.ko",
    "usbserial.ko",
    "vcan.ko",
    "vcpu_stall_detector.ko",
    "virtio_balloon.ko",
    "virtio_blk.ko",
    "virtio_console.ko",
    "virtio_pci.ko",
    "virtio_pci_legacy_dev.ko",
    "virtio_pci_modern_dev.ko",
    "vmw_vsock_virtio_transport.ko",
    "wwan.ko",
    "xhci-pci-renesas.ko",
    "zram.ko",
    "zsmalloc.ko",
]

kernel_build(
    name = "mindone",
    srcs = ["//common:kernel_aarch64_sources"],
    outs = [
        "Image",
        "Image.gz",
        "System.map",
        "modules.builtin",
        "modules.builtin.modinfo",
        "vmlinux",
        "vmlinux.symvers",
    ],
    arch = "arm64",
    ddk_module_headers = ["//common:all_headers_aarch64"],
    defconfig = "//common:arch/arm64/configs/gki_defconfig",
    kmi_symbol_list = "//common:gki/aarch64/symbols/mindone",
    post_defconfig_fragments = ["mindone.fragment"],
    make_goals = [
        "Image",
        "Image.gz",
        "modules",
    ],
    makefile = "//common:Makefile",
    module_outs = _MINDONE_IN_TREE_MODULES,
    strip_modules = True,
    trim_nonlisted_kmi = False,
)

kernel_modules_install(
    name = "mindone_modules_install",
    kernel_build = ":mindone",
    kernel_modules = ["//common/mindone/modules:mindone_modules"],
)

kernel_abi(
    name = "mindone_abi",
    kernel_build = ":mindone",
    kernel_modules = ["//common/mindone/modules:mindone_modules"],
    kernel_modules_exclude_list = [
        "mtk_vow.ko",
        "mtk_scp_vow.ko",
    ],
)

kernel_compile_commands(
    name = "mindone_compile_commands",
    deps = [
        ":mindone",
        "//common/mindone/modules:mindone_modules",
    ],
)
