load(
    "//build/kernel/kleaf:kernel.bzl",
    "dtbo",
    "kernel_abi",
    "kernel_build",
    "kernel_compile_commands",
    "kernel_images",
    "kernel_modules_install",
)

package(default_visibility = ["//visibility:public"])

_MINDONE_IN_TREE_MODULES = [
    "8250_mtk.ko",
    "cfg80211.ko",
    "clk-mediatek.ko",
    "clk-mt6789.ko",
    "deferred-free-helper.ko",
    "drm_display_helper.ko",
    "drm_dma_helper.ko",
    "industrialio-triggered-buffer.ko",
    "kfifo_buf.ko",
    "mac80211.ko",
    "mtk-eint.ko",
    "page_pool.ko",
    "phy-mtk-ufs.ko",
    "pinctrl-mt6789.ko",
    "pinctrl-mtk-common-v2.ko",
    "pinctrl-paris.ko",
    "reset-ti-syscon.ko",
    "ufs-mediatek.ko",
]

kernel_build(
    name = "mindone",
    srcs = ["//common:kernel_aarch64_sources"],
    outs = [
        "arch/arm64/boot/dts/mediatek/mindone.dtb",
        "arch/arm64/boot/dts/mediatek/mindone-overlay.dtbo",
    ],
    arch = "arm64",
    base_kernel = "//common:kernel_aarch64",
    ddk_module_headers = ["//common:all_headers_aarch64"],
    defconfig = "//common:arch/arm64/configs/gki_defconfig",
    kmi_symbol_list = "//common:gki/aarch64/symbols/mindone",
    trim_nonlisted_kmi = True,
    pre_defconfig_fragments = ["mindone.fragment"],
    make_goals = [
        "modules",
        "mediatek/mindone.dtb",
        "mediatek/mindone-overlay.dtbo",
    ],
    makefile = "//common:Makefile",
    module_outs = _MINDONE_IN_TREE_MODULES,
    collect_unstripped_modules = True,
    strip_modules = True,
)

kernel_modules_install(
    name = "mindone_modules_install",
    kernel_build = ":mindone",
    kernel_modules = ["//common/mindone/modules:mindone_modules"],
)

kernel_images(
    name = "mindone_images",
    build_initramfs = True,
    build_vendor_dlkm = True,
    kernel_build = ":mindone",
    kernel_modules_install = ":mindone_modules_install",
    modules_list = "vendor_boot.modules.load",
    modules_recovery_list = "vendor_boot.modules.load.recovery",
    vendor_dlkm_modules_list = "vendor_dlkm.modules.load",
)

dtbo(
    name = "mindone_dtbo",
    srcs = [":mindone/mindone-overlay.dtbo"],
    kernel_build = ":mindone",
)

kernel_abi(
    name = "mindone_abi",
    kernel_build = ":mindone",
    kernel_modules = ["//common/mindone/modules:mindone_modules"],
)

kernel_compile_commands(
    name = "mindone_compile_commands",
    deps = [
        ":mindone",
        "//common/mindone/modules:mindone_modules",
    ],
)
