obj-m += soc_temp_lvts.o
soc_temp_lvts-objs := src/soc_temp_lvts.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)
ccflags-y += -I$(src)/../include
