ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -DCONFIG_MACH_MT6771=1 -DCONFIG_OF=1
subdir-ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -DCONFIG_MACH_MT6771=1 -DCONFIG_OF=1

ccflags-y += -I$(src)/inc
ccflags-y += -I$(src)/common/lc898122af
ccflags-y += -I$(src)/common/lc898212xdaf/inc
ccflags-y += -I$(src)/common/bu63169af/inc
subdir-ccflags-y += -I$(src)/inc
subdir-ccflags-y += -I$(src)/common/lc898122af
subdir-ccflags-y += -I$(src)/common/lc898212xdaf/inc
subdir-ccflags-y += -I$(src)/common/bu63169af/inc

obj-m += mainaf.o
mainaf-y := \
	main_lens.o \
	common/gt9767af/GT9767AF.o \
	common/gt9778af/GT9778AF.o \
	common/aw8601csr/AW8601CSR.o \
	common/gt9764baf/GT9764BAF.o \
	common/gt9772af/GT9772AF.o \
	common/pd9402aaf/PD9402A.o \
	common/fp5510e2af/FP5510E2AF.o \
	common/bu6424af/BU6424AF.o \
	common/bu6429af/BU6429AF.o \
	common/bu64748af/bu64748_function.o \
	common/bu64748af/bu64748af.o \
	common/dw9714af/DW9714AF.o \
	common/dw9800waf/DW9800WAF.o \
	common/dw9814af/DW9814AF.o \
	common/dw9718af/DW9718AF.o \
	common/dw9718saf/DW9718SAF.o \
	common/dw9718taf/DW9718TAF.o \
	common/dw9719taf/DW9719TAF.o \
	common/dw9763af/DW9763AF.o \
	common/dw9839af/DW9839AF.o \
	common/gt9764af/GT9764AF.o \
	common/gt9768af/GT9768AF.o \
	common/lc898212af/LC898212AF.o \
	common/lc898212xdaf/LC898212XDAF.o \
	common/lc898212xdaf/AfInter.o \
	common/lc898212xdaf/AfInit.o \
	common/lc898212xdaf/AfSTMV.o \
	common/lc898214af/LC898214AF.o \
	common/lc898217af/LC898217AF.o \
	common/lc898217afa/LC898217AFA.o \
	common/lc898217afb/LC898217AFB.o \
	common/lc898217afc/LC898217AFC.o \
	common/lc898229af/LC898229AF.o \
	common/lc898122af/LC898122AF.o \
	common/lc898122af/OisCmd.o \
	common/lc898122af/OisIni.o \
	common/wv511aaf/WV511AAF.o \
	common/ak7371af/AK7371AF.o \
	common/bu63169af/BU63169AF.o \
	common/bu63169af/OIS_func.o \
	common/bu63169af/OIS_main.o \
	common/bu63169af/OIS_user.o \
	common/bu64253gwzaf/BU64253GWZAF.o
ccflags-y += -I$(src)/../include
