# ../include/: MediaTek platform headers mirrored at their kernel-tree paths (shared by all modules)
obj-m += vcp_status.o
ccflags-y += -Wno-error -I$(src) -I$(src)/../include/drivers/misc/mediatek/vcp/include -I$(src)/../include/drivers/misc/mediatek/include -I$(src)/../include/drivers/misc/mediatek/vcp/rv -I$(src)/../include/drivers/misc/mediatek/include/mt-plat -I$(src)/../include/drivers/clk/mediatek
ccflags-y += -I$(src)/../include/include
