obj-m += snd_soc_mt6366.o
snd_soc_mt6366-objs := mt6358.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) -I$(src)/../include
include $(src)/../include/mindone/flags-audio.mk
