obj-m += mt6397.o
mt6397-objs := mt6397-core.o mt6397-irq.o mt6358-irq.o

ccflags-y += -I$(src)
ccflags-y += -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion
