obj-m += mtk_afe_external.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) -I$(src)/../include
include $(src)/../include/mindone/flags-audio.mk
