obj-m += task_turbo.o
ccflags-y += -Wno-error -Wno-error=implicit-int -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) -I$(src)/../include -I$(srctree)/kernel/ -I$(srctree)/drivers/android/ -include linux/sched/cputime.h
