obj-m += mtk_icc_core.o
mtk_icc_core-objs := core.o
ccflags-y += -DCONFIG_INTERCONNECT_MTK_EXTENSION=1 -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) 
ccflags-y += -I$(src)/../include
