obj-m += nvmem_mt635x_efuse.o
nvmem_mt635x_efuse-objs := mt635x-efuse.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) 
ccflags-y += -I$(src)/../include
