obj-m += btif_drv.o
btif_drv-objs := mtk_btif.o mtk_btif_exp.o btif_dma_plat.o btif_plat.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src) -DCONFIG_ARCH_MT6580=1 -DCONFIG_ARCH_MT6735=1 -DCONFIG_ARCH_MT6735M=1 -DCONFIG_ARCH_MT6753=1 -DCONFIG_MTK_GMO_RAM_OPTIMIZE=1
