obj-m += pd_chk_mt6789.o
pd_chk_mt6789-objs := mtk-pd-chk-mt6789.o
ccflags-y += -Wno-error -Wno-error=strict-prototypes -Wno-error=incompatible-pointer-types -Wno-error=int-conversion -I$(src)  -I$(src)/../include
